### ISSUE TITLE
No logging on RHEL based systems

### ISSUE THREAD

**Issue by marco-hoyer** [ImmobilienScout24/yaml-server#8]
Logging uses the /dev/log syslogd socket. This doesn't work on RHEL bases systems. Testen on Scientific Linux 6.4 and 6.5. The python stacktrace is:

  Traceback (most recent call last):
    File "/etc/init.d/yaml_server", line 25, in <module>
      sys.exit(yaml_server.YamlServerMain.YamlServerMain().service_script())
    File "/usr/lib/python2.6/site-packages/yaml_server/YamlServerMain.py", line 26, in **init**
      self.loghandler = logging.handlers.SysLogHandler(address='/dev/log')
    File "/usr/lib64/python2.6/logging/handlers.py", line 721, in **init**
      self._connect_unixsocket(address)
    File "/usr/lib64/python2.6/logging/handlers.py", line 737, in _connect_unixsocket
      self.socket.connect(address)
    File "<string>", line 1, in connect
  socket.error: [Errno 111] Connection refused

The process doesn't use the socket. No logging occures in messages.

Files opened by the yaml_server process:
sudo ls -al /proc/15688/fd/
insgesamt 0
dr-x------ 2 root   root    0 17. Mär 15:22 .
dr-xr-xr-x 8 nobody nobody  0 17. Mär 15:22 ..
lr-x------ 1 root   root   64 17. Mär 15:22 0 -> /dev/null
lrwx------ 1 root   root   64 17. Mär 15:22 1 -> /dev/null
lrwx------ 1 root   root   64 17. Mär 15:22 2 -> /dev/null
lrwx------ 1 root   root   64 17. Mär 15:22 3 -> socket:[92457]
lr-x------ 1 root   root   64 17. Mär 15:22 4 -> /dev/null
lrwx------ 1 root   root   64 17. Mär 15:22 5 -> /dev/null
lrwx------ 1 root   root   64 17. Mär 15:22 6 -> /dev/null
lrwx------ 1 root   root   64 17. Mär 15:22 7 -> socket:[92491]

there is one tcp socket, yaml_server is bound and only one other socket. There seems to be no corresponding file for that inode:

sudo find /\* -type f -inum 92457
no result

**Comment by snordhausen** [comment]
The difference between `DEBUG` and `--debug` is due to `--debug` taking effect early enough to [log the config settings](https://github.com/ImmobilienScout24/yaml-server/blob/master/src/yaml_server/YamlServerMain.py#L43).

Logging on CentOS7 works, since it has a /dev/log.

Logging on ScientificLinux 6.8 also works, /dev/log exists. Activating debug output has no effect, though, since rsyslog.conf configures log level `INFO` for messages to `/var/log/messages`.

I added a simple fallback to use syslog via UDP in case /dev/log does not exist, since I recall seeing such cases myself.
